### ISSUE TITLE
OptionMenu widget doesn't behave as before the clean up

### ISSUE THREAD

**Issue by sbordeyne** [Dogeek/DnDApp#4]
tried to import the tkinter.ttk widget 'OptionMenu' but that didn't fix it.

**Comment by solumos** [comment]
Did you try:

``` python
from tkinter.ttk import OptionMenu
```

**Comment by Sinderella** [comment]
I have no experience with tkinter, feel free to fix it. I'm just trying to set things up.

**Comment by sbordeyne** [comment]
i tried the tkinter.ttk but didn't work
